### ISSUE TITLE
Which distro/ kernel headers do you compile against?

### ISSUE THREAD

**Issue by mpasserini** [dagargo/emu3fs#12]
I'm trying to compile against "Linux vbox 6.1.0-28-amd64 #1 SMP PREEMPT_DYNAMIC Debian 6.1.119-1 (2024-11-22) x86_64 GNU/Linux" but I get lots of errors

Starting from:
```

/emu3fs/inode.c:208:9: error: implicit declaration of function 'inode_set_mtime_to_ts'; did you mean 'inode_set_ctime_to_ts'? [-Werror=implicit-function-declaration]
  208 |         inode_set_mtime_to_ts(inode, tv);
      |         ^~~~~~~~~~~~~~~~~~~~~
      |         inode_set_ctime_to_ts

```

to
```

/file.c:99:53: error: passing argument 4 of 'block_write_begin' from incompatible pointer type [-Werror=incompatible-pointer-types]
   99 |         return block_write_begin(mapping, pos, len, foliop, emu3_get_block);
      |                                                     ^~~~~~
      |                                                     |
      |                                                     struct folio **

```
etc.

Which distro do you suggest using?

**Comment by dagargo** [comment]
I think the issue is that you haven't checked out the appropriate tag. As emu3fs is outside the kernel, and needing it to be compatible with all versions, there is a tag for every supported kernel version. So, in your case, try `git checkout 6.1` and compile again.

This is explained here.

https://github.com/dagargo/emu3fs?tab=readme-ov-file#installation

Let me know if that fixes the issues for you.

**Comment by mpasserini** [comment]
It worked, thanks!
